ALTER TABLE shifts ADD COLUMN opening_gcash NUMERIC(12,2) DEFAULT 0;
ALTER TABLE shifts ADD COLUMN closing_gcash NUMERIC(12,2) DEFAULT 0;
ALTER TABLE shifts ADD COLUMN gcash_sales NUMERIC(12,2) DEFAULT 0;
